### ISSUE TITLE
"LED4"?

### ISSUE THREAD

**Issue by lars-t-hansen** [knowit/stm32-bare-metal#1]
I `https://github.com/knowit/stm32-bare-metal/blob/main/doc/2_blinky.md` nevnes "LED4" plutselig mens tidligere har LED_GREEN blitt brukt.

**Comment by lars-t-hansen** [comment]
I del 3 av kurset beskrives LED'en som "LD4" og ikke "LED4", bare for å gjøre det litt mer forvirrende.  Det er antakelig "LD4" som står på kortet (som jeg ikke har foran meg).

**Comment by lars-t-hansen** [comment]
Senere i del 3 er "LED4" brukt igjen.

**Comment by beachviking** [comment]
Har gått igjennom og ryddet opp i dette.  Har også markert led på utviklerkortet i bildet av denne.
