### ISSUE TITLE
Det er alltid feil å velge frequency=0 i rtttl_play() om data mangler

### ISSUE THREAD

**Issue by lars-t-hansen** [knowit/stm32-bare-metal#10]
Vi har:
```
frequency = note ? notes[(scale - 4) * 12 + note] : 0
```
Her vil default-verdien 0 gi opphav til en mystisk hardfault i `rtttl_set_frequency()`.  En bedre default ville være en note som kan høres, gjerne en vi ikke forventer å høre i en melodi.

**Comment by beachviking** [comment]
Fixed with NOTE_C4 instead.  Makes it more clear for people to customize this to their liking.  An alternative could also be PAUSE.
