### ISSUE TITLE
Hvorfor osDelay i vLedTask?

### ISSUE THREAD

**Issue by lars-t-hansen** [knowit/stm32-bare-metal#4]
Det er et delay i denne løkka etterfulgt av en blokkerende wait:
```
osDelay(100);
/*wait until kernel message*/
event = osMessageGet(myEventQueueHandle, osWaitForever);
```
Virker unødvendig?  Bør ihvertfall motiveres på en eller annen måte.  For knappen er det jo polling, men ikke her.

**Comment by beachviking** [comment]
Ikke nødvendig, har ryddet i dette.  Krasj mellom kodegenerert logikk og egen. :)
