### ISSUE TITLE
Avspillingslogikk

### ISSUE THREAD

**Issue by lars-t-hansen** [knowit/stm32-bare-metal#9]
Det er noe som skurrer litt for meg (ha ha) i vPlayerTask.  Først venter vi 10ms (hvorfor det?), deretter opptil 50ms for et event.  Maks - og faktisk forventet, ettersom det sjelden er events - ventetid er altså 60ms eller ~1/17s (i tillegg til at dette er en Idle-prioritets thread, som nevnt tidligere, og kan stoppes når som helst av hva som helst), og dette er så ofte som vi får anledning til å kjøre rtttl_play().  Dette kan framstå som litt sjelden?  I tillegg har rtttl_play() en egen sjekk på at nok tid har gått for den tonen vi sender, men denne har kanskje noen edge effects fx slik at det er mulig for programmet å sjekke tick count noen mikrosekunder før den ruller over til neste ms og detter blir vi altså sittende og vente 60ms til neste tick?

Neppe fatalt for eksperimentet men kanskje noe verd å tenke på likevel.

**Comment by beachviking** [comment]
Endret timer verdier og fjernet redundante pauser.  Litt leftover kode/logikk mellom generert og utviklet kode.
